name: auto-update

on:
  workflow_dispatch:
  schedule:
    - cron:  0 1,5,9,13,17,21 * * *

jobs:
  build:
    name: auto update
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: liamg/github-profile-terminal-action@main
      with:
        feed_url: https://lia.mg/feed.xml
        twitter_username: liam_galvin
        theme: dark
        token: ${{ secrets. GITHUB_TOKEN }}
